name: 'CloudExpat Cost Report'
description: 'Post cloud cost and carbon footprint reports to your Pull Requests'
author: 'CloudExpat'

branding:
  icon: 'dollar-sign'
  color: 'green'

inputs:
  api-key:
    description: 'Your CloudExpat API key (from app.cloudexpat.com/dashboard/settings/api-keys)'
    required: true
  api-url:
    description: 'CloudExpat API URL (optional, for testing)'
    required: false
    default: 'https://data.cloudexpat.com'
  post-comment:
    description: 'Post report as PR comment (true/false)'
    required: false
    default: 'true'

outputs:
  report-file:
    description: 'Path to the generated report file'
    value: ${{ steps.fetch-report.outputs.report-file }}
  success:
    description: 'Whether the report was fetched successfully'
    value: ${{ steps.fetch-report.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Fetch Cost Report from CloudExpat
      id: fetch-report
      shell: bash
      run: |
        if [ -z "${{ inputs.api-key }}" ]; then
          echo "::error::CloudExpat API key is required"
          exit 1
        fi

        echo "Fetching cost report from CloudExpat..."

        RESPONSE=$(curl -s -w "\n%{http_code}" \
          "${{ inputs.api-url }}/v1/report?format=markdown" \
          -H "Authorization: Bearer ${{ inputs.api-key }}" \
          -H "Content-Type: application/json")

        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')

        if [ "$HTTP_CODE" != "200" ]; then
          echo "::error::Failed to fetch report. HTTP $HTTP_CODE"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Save report to file
        echo "$BODY" > cloudexpat-report.md

        # Output for other steps
        echo "report-file=cloudexpat-report.md" >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT

        # Add to job summary
        cat cloudexpat-report.md >> $GITHUB_STEP_SUMMARY

    - name: Post Report as PR Comment
      if: github.event_name == 'pull_request' && inputs.post-comment == 'true' && steps.fetch-report.outputs.success == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('cloudexpat-report.md', 'utf8');

          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c =>
            c.user.type === 'Bot' && c.body.includes('CloudExpat Cost Report')
          );

          const body = report + '\n\n---\n<sub>Generated by [CloudExpat](https://cloudexpat.com) | [Get your API key](https://app.cloudexpat.com/dashboard/settings/api-keys)</sub>';

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body: body
            });
            console.log('Updated existing CloudExpat comment');
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
            console.log('Created new CloudExpat comment');
          }
